return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 960,
  h = 640,
  shellLayout = {
    mode = "fill",
    designW = 960,
    designH = 640,
  },
  style = {
    bg = 0xff020617,
  },
  behavior = "ui/behaviors/main.lua",
  children = {
    {
      id = "header",
      type = "Panel",
      x = 0,
      y = 0,
      w = 960,
      h = 72,
      style = {
        bg = 0xff111827,
        radius = 0,
      },
    },
    {
      id = "title",
      type = "Label",
      x = 16,
      y = 8,
      w = 260,
      h = 22,
      props = { text = "Webcam Viewer" },
      style = {
        colour = 0xffffffff,
        fontSize = 18,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "rendererMode",
      type = "Label",
      x = 16,
      y = 34,
      w = 320,
      h = 18,
      props = { text = "Renderer: --" },
      style = {
        colour = 0xff93c5fd,
        fontSize = 12,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "deviceSelect",
      type = "Dropdown",
      x = 336,
      y = 10,
      w = 400,
      h = 24,
      props = {
        options = { "No devices found" },
        selected = 1,
      },
      style = {
        bg = 0xff1e293b,
        colour = 0xff38bdf8,
        border = 0xff334155,
        borderWidth = 1,
      },
    },
    {
      id = "modeSelect",
      type = "Dropdown",
      x = 336,
      y = 38,
      w = 400,
      h = 24,
      props = {
        options = { "No modes found" },
        selected = 1,
      },
      style = {
        bg = 0xff0f172a,
        colour = 0xfff59e0b,
        border = 0xff334155,
        borderWidth = 1,
      },
    },
    {
      id = "refreshBtn",
      type = "Button",
      x = 748,
      y = 10,
      w = 80,
      h = 24,
      props = { label = "Refresh" },
      style = {
        bg = 0xff2563eb,
        border = 0xff60a5fa,
        borderWidth = 1,
        fontSize = 12,
      },
    },
    {
      id = "openBtn",
      type = "Button",
      x = 834,
      y = 10,
      w = 80,
      h = 24,
      props = { label = "Open" },
      style = {
        bg = 0xff15803d,
        border = 0xff22c55e,
        borderWidth = 1,
        fontSize = 12,
      },
    },
    {
      id = "closeBtn",
      type = "Button",
      x = 834,
      y = 38,
      w = 80,
      h = 24,
      props = { label = "Close" },
      style = {
        bg = 0xff7f1d1d,
        border = 0xffef4444,
        borderWidth = 1,
        fontSize = 12,
      },
    },
    {
      id = "status",
      type = "Label",
      x = 16,
      y = 80,
      w = 928,
      h = 20,
      props = { text = "Scanning video devices..." },
      style = {
        colour = 0xffcbd5e1,
        fontSize = 13,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "frameInfo",
      type = "Label",
      x = 16,
      y = 100,
      w = 928,
      h = 16,
      props = { text = "Frame: --" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 11,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "viewport",
      type = "Panel",
      x = 16,
      y = 120,
      w = 928,
      h = 240,
      style = {
        bg = 0xff000000,
        border = 0xff334155,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "fxPanel",
      type = "Panel",
      x = 16,
      y = 368,
      w = 928,
      h = 248,
      style = {
        bg = 0xff0b1220,
        border = 0xff1e293b,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "layerTabs",
      type = "SegmentedControl",
      x = 28,
      y = 378,
      w = 360,
      h = 22,
      props = {
        segments = { "Layer 1", "Layer 2", "Layer 3", "Layer 4" },
        selected = 1,
      },
      style = {
        bg = 0xff1e293b,
        selectedBg = 0xff7c3aed,
        textColour = 0xff94a3b8,
        selectedTextColour = 0xffffffff,
      },
    },
    {
      id = "layerEnabledBtn",
      type = "Button",
      x = 396,
      y = 378,
      w = 80,
      h = 22,
      props = { label = "On" },
      style = {
        bg = 0xff15803d,
        border = 0xff22c55e,
        borderWidth = 1,
        fontSize = 11,
      },
    },
    {
      id = "layerDescription",
      type = "Label",
      x = 484,
      y = 378,
      w = 448,
      h = 22,
      props = { text = "Select an effect for this pass" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 11,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "effectSelect",
      type = "Dropdown",
      x = 28,
      y = 410,
      w = 200,
      h = 24,
      props = {
        options = { "Passthrough" },
        selected = 1,
      },
      style = {
        bg = 0xff1a1630,
        colour = 0xffc084fc,
        border = 0xff4c1d95,
        borderWidth = 1,
      },
    },
    {
      id = "clearLayerBtn",
      type = "Button",
      x = 822,
      y = 410,
      w = 110,
      h = 24,
      props = { label = "Clear Layer" },
      style = {
        bg = 0xff7f1d1d,
        border = 0xffef4444,
        borderWidth = 1,
        fontSize = 11,
      },
    },
    {
      id = "fxParam1",
      type = "Slider",
      x = 28,
      y = 446,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 1", compact = true, showValue = true },
      style = { colour = 0xff38bdf8, bg = 0xff102033, fontSize = 9 },
    },
    {
      id = "fxParam2",
      type = "Slider",
      x = 328,
      y = 446,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 2", compact = true, showValue = true },
      style = { colour = 0xff22c55e, bg = 0xff102717, fontSize = 9 },
    },
    {
      id = "fxParam3",
      type = "Slider",
      x = 628,
      y = 446,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 3", compact = true, showValue = true },
      style = { colour = 0xfff59e0b, bg = 0xff2f1e08, fontSize = 9 },
    },
    {
      id = "fxParam4",
      type = "Slider",
      x = 28,
      y = 480,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 4", compact = true, showValue = true },
      style = { colour = 0xfffb7185, bg = 0xff34111a, fontSize = 9 },
    },
    {
      id = "fxParam5",
      type = "Slider",
      x = 328,
      y = 480,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 5", compact = true, showValue = true },
      style = { colour = 0xffa78bfa, bg = 0xff1e1b33, fontSize = 9 },
    },
    {
      id = "fxParam6",
      type = "Slider",
      x = 628,
      y = 480,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 6", compact = true, showValue = true },
      style = { colour = 0xff22d3ee, bg = 0xff08212a, fontSize = 9 },
    },
    {
      id = "fxParam7",
      type = "Slider",
      x = 28,
      y = 514,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 7", compact = true, showValue = true },
      style = { colour = 0xfff97316, bg = 0xff2a1208, fontSize = 9 },
    },
    {
      id = "fxParam8",
      type = "Slider",
      x = 328,
      y = 514,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 8", compact = true, showValue = true },
      style = { colour = 0xff34d399, bg = 0xff10231d, fontSize = 9 },
    },
    {
      id = "fxParam9",
      type = "Slider",
      x = 628,
      y = 514,
      w = 290,
      h = 26,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 9", compact = true, showValue = true },
      style = { colour = 0xfffbbf24, bg = 0xff2b2008, fontSize = 9 },
    },
    {
      id = "fxHint",
      type = "Label",
      x = 28,
      y = 550,
      w = 900,
      h = 44,
      props = { text = "Stack up to 4 shader passes. Each pass feeds its output into the next — a true sequential shader pipeline." },
      style = {
        colour = 0xff64748b,
        fontSize = 11,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "hint",
      type = "Label",
      x = 16,
      y = 622,
      w = 928,
      h = 16,
      props = { text = "imgui-direct renderer required for live video surfaces and video synth shaders" },
      style = {
        colour = 0xff64748b,
        fontSize = 11,
        justification = Justify.centredLeft,
      },
    },
  },
}
