return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 960,
  h = 640,
  shellLayout = {
    mode = "fill",
    designW = 960,
    designH = 640,
  },
  style = {
    bg = 0xff020617,
  },
  behavior = "ui/behaviors/main.lua",
  children = {
    {
      id = "header",
      type = "Panel",
      x = 0,
      y = 0,
      w = 960,
      h = 72,
      style = {
        bg = 0xff111827,
        radius = 0,
      },
    },
    {
      id = "title",
      type = "Label",
      x = 16,
      y = 8,
      w = 260,
      h = 22,
      props = { text = "Webcam Viewer" },
      style = {
        colour = 0xffffffff,
        fontSize = 18,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "rendererMode",
      type = "Label",
      x = 16,
      y = 34,
      w = 320,
      h = 18,
      props = { text = "Renderer: --" },
      style = {
        colour = 0xff93c5fd,
        fontSize = 12,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "deviceSelect",
      type = "Dropdown",
      x = 336,
      y = 10,
      w = 400,
      h = 24,
      props = {
        options = { "No devices found" },
        selected = 1,
      },
      style = {
        bg = 0xff1e293b,
        colour = 0xff38bdf8,
        border = 0xff334155,
        borderWidth = 1,
      },
    },
    {
      id = "modeSelect",
      type = "Dropdown",
      x = 336,
      y = 38,
      w = 400,
      h = 24,
      props = {
        options = { "No modes found" },
        selected = 1,
      },
      style = {
        bg = 0xff0f172a,
        colour = 0xfff59e0b,
        border = 0xff334155,
        borderWidth = 1,
      },
    },
    {
      id = "refreshBtn",
      type = "Button",
      x = 748,
      y = 10,
      w = 80,
      h = 24,
      props = { label = "Refresh" },
      style = {
        bg = 0xff2563eb,
        border = 0xff60a5fa,
        borderWidth = 1,
        fontSize = 12,
      },
    },
    {
      id = "openBtn",
      type = "Button",
      x = 834,
      y = 10,
      w = 80,
      h = 24,
      props = { label = "Open" },
      style = {
        bg = 0xff15803d,
        border = 0xff22c55e,
        borderWidth = 1,
        fontSize = 12,
      },
    },
    {
      id = "closeBtn",
      type = "Button",
      x = 834,
      y = 38,
      w = 80,
      h = 24,
      props = { label = "Close" },
      style = {
        bg = 0xff7f1d1d,
        border = 0xffef4444,
        borderWidth = 1,
        fontSize = 12,
      },
    },
    {
      id = "status",
      type = "Label",
      x = 16,
      y = 80,
      w = 928,
      h = 24,
      props = { text = "Scanning video devices..." },
      style = {
        colour = 0xffcbd5e1,
        fontSize = 13,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "frameInfo",
      type = "Label",
      x = 16,
      y = 100,
      w = 928,
      h = 16,
      props = { text = "Frame: --" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 11,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "viewport",
      type = "Panel",
      x = 16,
      y = 122,
      w = 928,
      h = 360,
      style = {
        bg = 0xff000000,
        border = 0xff334155,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "fxPanel",
      type = "Panel",
      x = 16,
      y = 494,
      w = 928,
      h = 124,
      style = {
        bg = 0xff0b1220,
        border = 0xff1e293b,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "fxTitle",
      type = "Label",
      x = 28,
      y = 504,
      w = 180,
      h = 18,
      props = { text = "Video Effect" },
      style = {
        colour = 0xfff8fafc,
        fontSize = 12,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "fxDescription",
      type = "Label",
      x = 240,
      y = 504,
      w = 676,
      h = 18,
      props = { text = "Shader effect applied to the live webcam feed" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 11,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "effectSelect",
      type = "Dropdown",
      x = 28,
      y = 532,
      w = 190,
      h = 24,
      props = {
        options = { "Passthrough" },
        selected = 1,
      },
      style = {
        bg = 0xff1a1630,
        colour = 0xffc084fc,
        border = 0xff4c1d95,
        borderWidth = 1,
      },
    },
    {
      id = "fxParam1",
      type = "Slider",
      x = 240,
      y = 530,
      w = 160,
      h = 24,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 1", compact = true, showValue = true },
      style = { colour = 0xff38bdf8, bg = 0xff102033, fontSize = 8 },
    },
    {
      id = "fxParam2",
      type = "Slider",
      x = 412,
      y = 530,
      w = 160,
      h = 24,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 2", compact = true, showValue = true },
      style = { colour = 0xff22c55e, bg = 0xff102717, fontSize = 8 },
    },
    {
      id = "fxParam3",
      type = "Slider",
      x = 584,
      y = 530,
      w = 160,
      h = 24,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 3", compact = true, showValue = true },
      style = { colour = 0xfff59e0b, bg = 0xff2f1e08, fontSize = 8 },
    },
    {
      id = "fxParam4",
      type = "Slider",
      x = 756,
      y = 530,
      w = 160,
      h = 24,
      props = { min = 0, max = 1, step = 0.01, value = 0.5, label = "Param 4", compact = true, showValue = true },
      style = { colour = 0xfffb7185, bg = 0xff34111a, fontSize = 8 },
    },
    {
      id = "fxHint",
      type = "Label",
      x = 28,
      y = 566,
      w = 888,
      h = 16,
      props = { text = "Video synth primitives are fed from the live webcam texture and rendered through first-party GLSL" },
      style = {
        colour = 0xff64748b,
        fontSize = 10,
        justification = Justify.centredLeft,
      },
    },
    {
      id = "hint",
      type = "Label",
      x = 16,
      y = 622,
      w = 928,
      h = 18,
      props = { text = "imgui-direct renderer required for live video surfaces and video synth shaders" },
      style = {
        colour = 0xff64748b,
        fontSize = 12,
        justification = Justify.centredLeft,
      },
    },
  },
}
