return {
  id = "layer_strip_root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 120,
  style = {
    bg = 0xff1b2636,
    radius = 8,
    border = 0xff334155,
    borderWidth = 1,
  },
  children = {
    {
      id = "label",
      type = "Label",
      x = 6,
      y = 6,
      w = 26,
      h = 24,
      props = { text = "L?" },
      style = { colour = 0xff94a3b8, fontSize = 15, fontStyle = "bold" },
    },
    {
      id = "state",
      type = "Label",
      x = 6,
      y = 38,
      w = 50,
      h = 20,
      props = { text = "" },
      style = { colour = 0xff64748b, fontSize = 11 },
    },
    {
      id = "bars",
      type = "Label",
      x = 6,
      y = 70,
      w = 50,
      h = 16,
      props = { text = "" },
      style = { colour = 0xff94a3b8, fontSize = 10 },
    },
    {
      id = "waveform",
      type = "WaveformView",
      x = 56,
      y = 6,
      w = 980,
      h = 108,
      props = { mode = "layer", layerIndex = 0 },
      style = { colour = 0xff22d3ee },
    },
    {
      id = "vol",
      type = "Knob",
      x = 1044,
      y = 6,
      w = 60,
      h = 108,
      props = {
        min = 0,
        max = 2,
        step = 0.01,
        value = 1.0,
        label = "Vol",
      },
      style = { colour = 0xffa78bfa },
    },
    {
      id = "speed",
      type = "Knob",
      x = 1108,
      y = 6,
      w = 60,
      h = 108,
      props = {
        min = -4.0,
        max = 4.0,
        step = 0.01,
        value = 1.0,
        label = "Speed",
      },
      style = { colour = 0xff22d3ee },
    },
    {
      id = "mute",
      type = "Button",
      x = 1172,
      y = 6,
      w = 44,
      h = 108,
      props = { label = "Mute" },
      style = { bg = 0xff475569, fontSize = 11 },
    },
    {
      id = "clear",
      type = "Button",
      x = 1220,
      y = 6,
      w = 28,
      h = 48,
      props = { label = "✕" },
      style = { bg = 0xff7f1d1d, fontSize = 11 },
    },
    {
      id = "play",
      type = "Button",
      x = 1220,
      y = 60,
      w = 28,
      h = 48,
      props = { label = "▶" },
      style = { bg = 0xff1f7a3a, fontSize = 13 },
    },
  },
  components = {},
}
