return {
  id = "transport_root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 48,
  style = {
    bg = 0xff141a24,
    radius = 8,
  },
  children = {
    {
      id = "mode",
      type = "Dropdown",
      x = 6,
      y = 6,
      w = 130,
      h = 36,
      props = {
        options = { "First Loop", "Free Mode", "Traditional" },
        selected = 1,
      },
      style = {
        bg = 0xff1f4a7a,
        colour = 0xff7dd3fc,
      },
    },
    {
      id = "rec",
      type = "Button",
      x = 144,
      y = 6,
      w = 80,
      h = 36,
      props = { label = "● REC" },
      style = { bg = 0xff7f1d1d, fontSize = 13 },
    },
    {
      id = "playpause",
      type = "Button",
      x = 230,
      y = 6,
      w = 80,
      h = 36,
      props = { label = "▶ PLAY" },
      style = { bg = 0xff1f7a3a, fontSize = 13 },
    },
    {
      id = "stop",
      type = "Button",
      x = 316,
      y = 6,
      w = 80,
      h = 36,
      props = { label = "⏹ STOP" },
      style = { bg = 0xff374151, fontSize = 13 },
    },
    {
      id = "overdub",
      type = "Toggle",
      x = 408,
      y = 6,
      w = 110,
      h = 36,
      props = { label = "Overdub", value = false },
      style = { onColour = 0xfff59e0b, offColour = 0xff374151 },
    },
    {
      id = "clearall",
      type = "Button",
      x = 530,
      y = 6,
      w = 70,
      h = 36,
      props = { label = "Clear All" },
      style = { bg = 0xff1f2937, fontSize = 12 },
    },
    {
      id = "linkIndicator",
      type = "Label",
      x = 930,
      y = 6,
      w = 50,
      h = 36,
      props = { text = "link" },
      style = { colour = 0xff4b5563, fontSize = 11 },
    },
    {
      id = "tempo",
      type = "NumberBox",
      x = 988,
      y = 6,
      w = 96,
      h = 36,
      props = {
        min = 40,
        max = 240,
        step = 1,
        value = 120,
        label = "BPM",
        format = "%d",
      },
      style = { colour = 0xff38bdf8 },
    },
    {
      id = "targetBpm",
      type = "NumberBox",
      x = 1092,
      y = 6,
      w = 96,
      h = 36,
      props = {
        min = 40,
        max = 240,
        step = 1,
        value = 120,
        label = "Target",
        format = "%d",
      },
      style = { colour = 0xff22d3ee },
    },
  },
  components = {},
}
