return {
  id = "settings_overlay_root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 472,
  h = 208,
  style = {
    bg = 0xff0f172a,
    border = 0xff334155,
    borderWidth = 1,
    radius = 0,
  },
  children = {
    {
      id = "settings_title",
      type = "Label",
      x = 16,
      y = 16,
      w = 200,
      h = 24,
      props = { text = "Settings" },
      style = { colour = 0xffffffff, fontSize = 14, bg = 0x00000000 },
    },
    {
      id = "close_button",
      type = "Button",
      x = 432,
      y = 12,
      w = 24,
      h = 24,
      props = { text = "X" },
      style = { colour = 0xffffffff, bg = 0x00000000, hoverBg = 0xff334155, fontSize = 12 },
    },
    {
      id = "osc_section_title",
      type = "Label",
      x = 16,
      y = 56,
      w = 120,
      h = 16,
      props = { text = "OSC / OSCQuery" },
      style = { colour = 0xffa78bfa, fontSize = 11, bg = 0x00000000 },
    },
    {
      id = "osc_label",
      type = "Label",
      x = 16,
      y = 82,
      w = 60,
      h = 20,
      props = { text = "OSC" },
      style = { colour = 0xffcbd5e1, fontSize = 10, bg = 0x00000000 },
    },
    {
      id = "osc_enabled_toggle",
      type = "Toggle",
      x = 70,
      y = 80,
      w = 60,
      h = 24,
      props = { value = true, onLabel = "ON", offLabel = "OFF" },
      style = { onColour = 0xff7c3aed, offColour = 0xff334155, textColour = 0xffffffff, fontSize = 9, radius = 4 },
    },
    {
      id = "query_label",
      type = "Label",
      x = 150,
      y = 82,
      w = 60,
      h = 20,
      props = { text = "Query" },
      style = { colour = 0xffcbd5e1, fontSize = 10, bg = 0x00000000 },
    },
    {
      id = "osc_query_toggle",
      type = "Toggle",
      x = 210,
      y = 80,
      w = 60,
      h = 24,
      props = { value = true, onLabel = "ON", offLabel = "OFF" },
      style = { onColour = 0xff2563eb, offColour = 0xff334155, textColour = 0xffffffff, fontSize = 9, radius = 4 },
    },
    {
      id = "osc_port_label",
      type = "Label",
      x = 16,
      y = 114,
      w = 60,
      h = 16,
      props = { text = "UDP Port" },
      style = { colour = 0xff94a3b8, fontSize = 9, bg = 0x00000000 },
    },
    {
      id = "osc_port_value",
      type = "Label",
      x = 80,
      y = 114,
      w = 60,
      h = 16,
      props = { text = "-" },
      style = { colour = 0xffffffff, fontSize = 9, bg = 0x00000000 },
    },
    {
      id = "query_port_label",
      type = "Label",
      x = 150,
      y = 114,
      w = 70,
      h = 16,
      props = { text = "HTTP Port" },
      style = { colour = 0xff94a3b8, fontSize = 9, bg = 0x00000000 },
    },
    {
      id = "query_port_value",
      type = "Label",
      x = 225,
      y = 114,
      w = 60,
      h = 16,
      props = { text = "-" },
      style = { colour = 0xffffffff, fontSize = 9, bg = 0x00000000 },
    },
    {
      id = "remote_section_title",
      type = "Label",
      x = 16,
      y = 146,
      w = 120,
      h = 16,
      props = { text = "Web Remote" },
      style = { colour = 0xff22d3ee, fontSize = 11, bg = 0x00000000 },
    },
    {
      id = "remote_host_label",
      type = "Label",
      x = 16,
      y = 172,
      w = 34,
      h = 16,
      props = { text = "Host" },
      style = { colour = 0xff94a3b8, fontSize = 9, bg = 0x00000000 },
    },
    {
      id = "remote_host_value",
      type = "Label",
      x = 52,
      y = 172,
      w = 92,
      h = 16,
      props = { text = "127.0.0.1" },
      style = { colour = 0xffffffff, fontSize = 9, bg = 0x00000000 },
    },
    {
      id = "remote_port_box",
      type = "NumberBox",
      x = 150,
      y = 164,
      w = 88,
      h = 24,
      props = {
        min = 1,
        max = 65535,
        step = 1,
        value = 18081,
        label = "Port",
        format = "%d",
      },
      style = { colour = 0xff22d3ee },
    },
    {
      id = "remote_status_label",
      type = "Label",
      x = 248,
      y = 172,
      w = 44,
      h = 16,
      props = { text = "Status" },
      style = { colour = 0xff94a3b8, fontSize = 9, bg = 0x00000000 },
    },
    {
      id = "remote_status_value",
      type = "Label",
      x = 296,
      y = 172,
      w = 120,
      h = 16,
      props = { text = "Idle" },
      style = { colour = 0xffffffff, fontSize = 9, bg = 0x00000000 },
    },
  },
}
