#!/usr/bin/env python3
"""
Manifold gRPC Python Client

Provides high-level access to the Manifold audio plugin for:
- Remote control and automation
- State monitoring and logging  
- DSP hot-reloading and testing
- Audio visualization
"""

import grpc
import numpy as np
import time
import threading
from contextlib import contextmanager
from typing import Optional, Callable, Iterator, List, Dict
from dataclasses import dataclass

# Generated protobuf modules (would be generated by protoc)
import manifold_pb2
import manifold_pb2_grpc


@dataclass
class LayerState:
    index: int
    state: str  # "empty", "playing", "recording", etc.
    length: int  # samples
    position: int  # samples
    position_norm: float  # 0-1
    speed: float
    reversed: bool
    volume: float
    muted: bool
    bars: float


@dataclass
class FullState:
    timestamp: float
    tempo: float
    target_bpm: float
    master_volume: float
    input_volume: float
    recording: bool
    overdub: bool
    mode: str
    active_layer: int
    layers: List[LayerState]
    link_peers: int
    link_playing: bool


class ManifoldClient:
    """High-level client for Manifold audio plugin."""
    
    def __init__(self, host: str = "localhost", port: int = 50051):
        self.channel = grpc.insecure_channel(f"{host}:{port}")
        self.stub = manifold_pb2_grpc.ManifoldControlStub(self.channel)
        self._state_callbacks: List[Callable[[FullState], None]] = []
        self._midi_callbacks: List[Callable[[manifold_pb2.MidiEvent], None]] = []
        self._streaming = False
        self._stream_thread: Optional[threading.Thread] = None
        
    def close(self):
        """Close the connection."""
        self.stop_streaming()
        self.channel.close()
        
    def __enter__(self):
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
        
    # -------------------------------------------------------------------------
    # Parameter Control
    # -------------------------------------------------------------------------
    
    def set_param(self, path: str, value: float) -> bool:
        """Set a parameter by path."""
        request = manifold_pb2.SetParameterRequest(
            path=path,
            value=manifold_pb2.ParameterValue(float_value=value)
        )
        response = self.stub.SetParameter(request)
        return response.success
    
    def get_param(self, path: str) -> Optional[float]:
        """Get a parameter value by path."""
        request = manifold_pb2.GetParameterRequest(path=path)
        response = self.stub.GetParameter(request)
        if response.exists and response.value.HasField("float_value"):
            return response.value.float_value
        return None
    
    def trigger(self, path: str) -> bool:
        """Trigger a parameter (like a button press)."""
        request = manifold_pb2.TriggerRequest(path=path)
        response = self.stub.Trigger(request)
        return response.success
    
    def set_params_batch(self, params: Dict[str, float]) -> bool:
        """Set multiple parameters at once."""
        def generate_requests():
            for path, value in params.items():
                yield manifold_pb2.SetParameterRequest(
                    path=path,
                    value=manifold_pb2.ParameterValue(float_value=value)
                )
        
        response = self.stub.SetParameters(generate_requests())
        return response.success
    
    # -------------------------------------------------------------------------
    # Transport Control
    # -------------------------------------------------------------------------
    
    def play(self):
        """Start playback."""
        self.stub.Play(manifold_pb2.Empty())
    
    def stop(self):
        """Stop playback."""
        self.stub.Stop(manifold_pb2.Empty())
    
    def pause(self):
        """Pause playback."""
        self.stub.Pause(manifold_pb2.Empty())
    
    def record(self):
        """Start recording."""
        self.stub.Record(manifold_pb2.Empty())
    
    def commit(self, bars: float = 4.0):
        """Commit recording with specified bar count."""
        request = manifold_pb2.CommitRequest(bars=bars)
        self.stub.Commit(request)
    
    def set_tempo(self, bpm: float):
        """Set tempo in BPM."""
        request = manifold_pb2.SetTempoRequest(bpm=bpm)
        self.stub.SetTempo(request)
    
    # -------------------------------------------------------------------------
    # State Queries
    # -------------------------------------------------------------------------
    
    def get_state(self) -> FullState:
        """Get full plugin state."""
        proto_state = self.stub.GetFullState(manifold_pb2.Empty())
        return self._convert_state(proto_state)
    
    def _convert_state(self, proto: manifold_pb2.FullState) -> FullState:
        """Convert protobuf state to Python dataclass."""
        layers = []
        for layer in proto.layers:
            layers.append(LayerState(
                index=layer.index,
                state=layer.state,
                length=layer.length,
                position=layer.position,
                position_norm=layer.position_norm,
                speed=layer.speed,
                reversed=layer.reversed,
                volume=layer.volume,
                muted=layer.muted,
                bars=layer.bars
            ))
        
        return FullState(
            timestamp=proto.timestamp,
            tempo=proto.tempo,
            target_bpm=proto.target_bpm,
            master_volume=proto.master_volume,
            input_volume=proto.input_volume,
            recording=proto.recording,
            overdub=proto.overdub,
            mode=proto.mode,
            active_layer=proto.active_layer,
            layers=layers,
            link_peers=proto.link.peers,
            link_playing=proto.link.playing
        )
    
    # -------------------------------------------------------------------------
    # Streaming
    # -------------------------------------------------------------------------
    
    def on_state_change(self, callback: Callable[[FullState], None]):
        """Register a callback for state changes."""
        self._state_callbacks.append(callback)
    
    def on_midi_event(self, callback: Callable[[manifold_pb2.MidiEvent], None]):
        """Register a callback for MIDI events."""
        self._midi_callbacks.append(callback)
    
    def start_streaming(self, delta_mode: bool = True):
        """Start background streaming of state/MIDI."""
        if self._streaming:
            return
            
        self._streaming = True
        self._stream_thread = threading.Thread(target=self._stream_loop, args=(delta_mode,))
        self._stream_thread.daemon = True
        self._stream_thread.start()
    
    def stop_streaming(self):
        """Stop background streaming."""
        self._streaming = False
        if self._stream_thread:
            self._stream_thread.join(timeout=1.0)
    
    def _stream_loop(self, delta_mode: bool):
        """Background thread for state streaming."""
        try:
            if delta_mode:
                stream = self.stub.SubscribeStateDeltas(manifold_pb2.StateFilter())
            else:
                stream = self.stub.SubscribeState(manifold_pb2.StateFilter())
            
            for update in stream:
                if not self._streaming:
                    break
                    
                if delta_mode:
                    # Delta updates - merge with last known state
                    pass  # Would implement state merging
                else:
                    # Full state updates
                    state = self._convert_state(update)
                    for callback in self._state_callbacks:
                        try:
                            callback(state)
                        except Exception as e:
                            print(f"State callback error: {e}")
                            
        except grpc.RpcError as e:
            if self._streaming:
                print(f"Streaming error: {e}")
    
    # -------------------------------------------------------------------------
    # DSP Scripting
    # -------------------------------------------------------------------------
    
    def load_dsp(self, lua_code: str, slot: str = "default", source_name: str = "python_client") -> bool:
        """Load DSP script from Lua code."""
        request = manifold_pb2.DspScript(
            source=lua_code,
            slot=slot,
            source_name=source_name
        )
        response = self.stub.LoadDspScript(request)
        return response.success
    
    def reload_dsp(self, slot: str = "default") -> bool:
        """Reload current DSP script."""
        response = self.stub.ReloadDspSlot(manifold_pb2.StringValue(value=slot))
        return response.success
    
    # -------------------------------------------------------------------------
    # MIDI
    # -------------------------------------------------------------------------
    
    def send_note_on(self, note: int, velocity: int = 100, channel: int = 1):
        """Send MIDI Note On."""
        request = manifold_pb2.NoteOnEvent(
            channel=channel,
            note=note,
            velocity=velocity
        )
        self.stub.SendNoteOn(request)
    
    def send_note_off(self, note: int, channel: int = 1):
        """Send MIDI Note Off."""
        request = manifold_pb2.NoteOffEvent(
            channel=channel,
            note=note,
            velocity=0
        )
        self.stub.SendNoteOff(request)
    
    def send_cc(self, cc: int, value: int, channel: int = 1):
        """Send MIDI Control Change."""
        request = manifold_pb2.ControlChangeEvent(
            channel=channel,
            cc=cc,
            value=value
        )
        self.stub.SendCC(request)
    
    # -------------------------------------------------------------------------
    # Visualization
    # -------------------------------------------------------------------------
    
    def get_waveform(self, layer_index: int = -1, num_buckets: int = 128) -> np.ndarray:
        """Get waveform data for visualization."""
        request = manifold_pb2.WaveformRequest(
            layer_index=layer_index,
            num_buckets=num_buckets
        )
        response = self.stub.GetWaveform(request)
        return np.array(response.peaks)
    
    def stream_waveform(self, layer_index: int = -1, num_buckets: int = 128) -> Iterator[np.ndarray]:
        """Stream waveform data continuously."""
        request = manifold_pb2.WaveformRequest(
            layer_index=layer_index,
            num_buckets=num_buckets
        )
        for response in self.stub.StreamWaveform(request):
            yield np.array(response.peaks)


# =============================================================================
# High-Level Testing Utilities
# =============================================================================

class DSPTestHarness:
    """Test harness for DSP development."""
    
    def __init__(self, client: ManifoldClient):
        self.client = client
        self.recorded_audio: List[np.ndarray] = []
    
    def load_oscillator(self, freq: float = 440.0, waveform: int = 1):
        """Load a simple oscillator DSP."""
        lua = f'''
function buildPlugin(ctx)
    local osc = ctx.primitives.OscillatorNode.new()
    osc:setWaveform({waveform})
    osc:setFrequency({freq})
    osc:setAmplitude(0.25)
    return {{}}
end
'''
        return self.client.load_dsp(lua)
    
    def assert_param(self, path: str, expected: float, tolerance: float = 0.01):
        """Assert a parameter value."""
        value = self.client.get_param(path)
        assert value is not None, f"Parameter {path} not found"
        assert abs(value - expected) < tolerance, \
            f"Expected {expected}, got {value} for {path}"
    
    def wait_for_state(self, condition: Callable[[FullState], bool], 
                       timeout: float = 5.0) -> bool:
        """Wait for a state condition to be met."""
        start = time.time()
        while time.time() - start < timeout:
            state = self.client.get_state()
            if condition(state):
                return True
            time.sleep(0.05)
        return False


# =============================================================================
# Example Usage
# =============================================================================

def example_basic_control():
    """Example: Basic transport and parameter control."""
    with ManifoldClient() as client:
        # Set tempo
        client.set_tempo(128.5)
        
        # Start recording
        client.record()
        time.sleep(2)
        
        # Commit 4 bars
        client.commit(4.0)
        
        # Play
        client.play()
        
        # Adjust layer 0 speed
        client.set_param("/core/behavior/layer/0/speed", 1.5)


def example_state_monitoring():
    """Example: Real-time state monitoring."""
    with ManifoldClient() as client:
        def on_state(state: FullState):
            print(f"Tempo: {state.tempo:.1f} BPM | "
                  f"Recording: {state.recording} | "
                  f"Layer 0: {state.layers[0].state}")
        
        client.on_state_change(on_state)
        client.start_streaming()
        
        # Run for 10 seconds
        time.sleep(10)


def example_dsp_hot_reload():
    """Example: Hot-reloading DSP from Python."""
    with ManifoldClient() as client:
        harness = DSPTestHarness(client)
        
        # Load oscillator
        harness.load_oscillator(freq=440.0, waveform=1)  # Saw
        time.sleep(2)
        
        # Switch to square wave
        harness.load_oscillator(freq=440.0, waveform=2)  # Square
        time.sleep(2)
        
        # Change frequency
        harness.load_oscillator(freq=880.0, waveform=2)


def example_midi_sequence():
    """Example: Play a MIDI sequence."""
    with ManifoldClient() as client:
        # C major arpeggio
        notes = [60, 64, 67, 72, 67, 64]  # C4, E4, G4, C5, G4, E4
        
        for note in notes:
            client.send_note_on(note, velocity=100)
            time.sleep(0.25)
            client.send_note_off(note)
            time.sleep(0.05)


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python manifold_client.py [example_name]")
        print("Examples: basic, monitor, dsp, midi")
        sys.exit(1)
    
    example = sys.argv[1]
    
    examples = {
        "basic": example_basic_control,
        "monitor": example_state_monitoring,
        "dsp": example_dsp_hot_reload,
        "midi": example_midi_sequence,
    }
    
    if example in examples:
        examples[example]()
    else:
        print(f"Unknown example: {example}")
        print(f"Available: {', '.join(examples.keys())}")
