return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  style = {
    bg = 4278849306,
  },
  behavior = "ui/behaviors/main.lua",
  children = {},
  components = {
    {
      id = "transport",
      x = 0,
      y = 0,
      w = 1280,
      h = 48,
      behavior = "ui/behaviors/transport.lua",
      ref = "ui/components/transport.ui.lua",
    },
    {
      id = "capture_plane",
      x = 0,
      y = 54,
      w = 1280,
      h = 130,
      behavior = "ui/behaviors/capture_plane.lua",
      ref = "ui/components/capture_plane.ui.lua",
    },
    {
      id = "layer0",
      x = 0,
      y = 190,
      w = 1280,
      h = 120,
      props = {
        layerIndex = 0,
      },
      behavior = "ui/behaviors/layer_strip.lua",
      ref = "ui/components/layer_strip.ui.lua",
    },
    {
      id = "layer1",
      x = 0,
      y = 316,
      w = 1280,
      h = 120,
      props = {
        layerIndex = 1,
      },
      behavior = "ui/behaviors/layer_strip.lua",
      ref = "ui/components/layer_strip.ui.lua",
    },
    {
      id = "layer2",
      x = 0,
      y = 442,
      w = 1280,
      h = 120,
      props = {
        layerIndex = 2,
      },
      behavior = "ui/behaviors/layer_strip.lua",
      ref = "ui/components/layer_strip.ui.lua",
    },
    {
      id = "layer3",
      x = 0,
      y = 568,
      w = 1280,
      h = 120,
      props = {
        layerIndex = 3,
      },
      behavior = "ui/behaviors/layer_strip.lua",
      ref = "ui/components/layer_strip.ui.lua",
    },
  },
}
