return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  style = {
    bg = 0xff08111f,
  },
  behavior = "ui/behaviors/main.lua",
  children = {
    {
      id = "header",
      type = "Panel",
      x = 16,
      y = 16,
      w = 1248,
      h = 86,
      style = {
        bg = 0xff111827,
        border = 0xff334155,
        borderWidth = 1,
        radius = 10,
      },
    },
    {
      id = "title",
      type = "Label",
      x = 32,
      y = 28,
      w = 360,
      h = 24,
      props = { text = "DSP LIVE SCRIPTING" },
      style = {
        colour = 0xffe2e8f0,
        fontSize = 22,
      },
    },
    {
      id = "subtitle",
      type = "Label",
      x = 32,
      y = 56,
      w = 520,
      h = 16,
      props = { text = "Structured user project demo: ImGui editor host + retained graph + widget runtime params" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 11,
      },
    },
    {
      id = "scriptDropdown",
      type = "Dropdown",
      x = 620,
      y = 28,
      w = 300,
      h = 28,
      props = {
        options = { "Loading DSP scripts..." },
        selected = 1,
        max_visible_rows = 10,
      },
      style = {
        bg = 0xff0f172a,
        colour = 0xff38bdf8,
      },
    },
    {
      id = "loadButton",
      type = "Button",
      x = 930,
      y = 28,
      w = 80,
      h = 28,
      props = { label = "Load" },
      style = { bg = 0xff334155, fontSize = 11 },
    },
    {
      id = "refreshButton",
      type = "Button",
      x = 1018,
      y = 28,
      w = 92,
      h = 28,
      props = { label = "Refresh" },
      style = { bg = 0xff334155, fontSize = 11 },
    },
    {
      id = "runButton",
      type = "Button",
      x = 1118,
      y = 28,
      w = 62,
      h = 28,
      props = { label = "Run" },
      style = { bg = 0xff0369a1, fontSize = 11 },
    },
    {
      id = "stopButton",
      type = "Button",
      x = 1188,
      y = 28,
      w = 60,
      h = 28,
      props = { label = "Stop" },
      style = { bg = 0xff9f1239, fontSize = 11 },
    },
    {
      id = "headerStatus",
      type = "Label",
      x = 620,
      y = 60,
      w = 628,
      h = 16,
      props = { text = "Ready" },
      style = {
        colour = 0xff7dd3fc,
        fontSize = 11,
        justification = Justify.centredRight,
      },
    },

    {
      id = "editorPanel",
      type = "Panel",
      x = 16,
      y = 114,
      w = 740,
      h = 590,
      style = {
        bg = 0xff111827,
        border = 0xff334155,
        borderWidth = 1,
        radius = 10,
      },
    },
    {
      id = "editorTitle",
      type = "Label",
      x = 30,
      y = 126,
      w = 240,
      h = 18,
      props = { text = "SCRIPT EDITOR" },
      style = {
        colour = 0xffe2e8f0,
        fontSize = 12,
      },
    },
    {
      id = "editorSubtext",
      type = "Label",
      x = 30,
      y = 146,
      w = 540,
      h = 16,
      props = { text = "Backed by the shared ImGui editor host. Edits stay renderer-agnostic." },
      style = {
        colour = 0xff94a3b8,
        fontSize = 10,
      },
    },
    {
      id = "editorHostFrame",
      type = "Panel",
      x = 30,
      y = 174,
      w = 712,
      h = 516,
      style = {
        bg = 0xff0b1220,
        border = 0xff334155,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "editorClosedLabel",
      type = "Label",
      x = 54,
      y = 404,
      w = 500,
      h = 22,
      props = { text = "Editor closed" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 12,
      },
    },
    {
      id = "openEditorButton",
      type = "Button",
      x = 54,
      y = 432,
      w = 120,
      h = 28,
      props = { label = "Open Editor" },
      style = { bg = 0xff1d4ed8, fontSize = 11 },
    },

    {
      id = "graphPanel",
      type = "Panel",
      x = 768,
      y = 114,
      w = 496,
      h = 274,
      style = {
        bg = 0xff111827,
        border = 0xff334155,
        borderWidth = 1,
        radius = 10,
      },
    },
    {
      id = "graphTitle",
      type = "Label",
      x = 784,
      y = 126,
      w = 220,
      h = 18,
      props = { text = "PARSED DSP GRAPH" },
      style = {
        colour = 0xffe2e8f0,
        fontSize = 12,
      },
    },
    {
      id = "graphSubtext",
      type = "Label",
      x = 784,
      y = 146,
      w = 452,
      h = 16,
      props = { text = "Retained display-list rendering. Drag inside to pan." },
      style = {
        colour = 0xff94a3b8,
        fontSize = 10,
      },
    },
    {
      id = "graphCanvas",
      type = "Panel",
      x = 784,
      y = 172,
      w = 464,
      h = 200,
      style = {
        bg = 0xff0b1220,
        border = 0xff334155,
        borderWidth = 1,
        radius = 8,
      },
    },

    {
      id = "paramsPanel",
      type = "Panel",
      x = 768,
      y = 400,
      w = 496,
      h = 304,
      style = {
        bg = 0xff111827,
        border = 0xff334155,
        borderWidth = 1,
        radius = 10,
      },
    },
    {
      id = "paramsTitle",
      type = "Label",
      x = 784,
      y = 412,
      w = 220,
      h = 18,
      props = { text = "RUNTIME PARAMETERS" },
      style = {
        colour = 0xffe2e8f0,
        fontSize = 12,
      },
    },
    {
      id = "paramState",
      type = "Label",
      x = 784,
      y = 434,
      w = 452,
      h = 16,
      props = { text = "No script loaded" },
      style = {
        colour = 0xffc4b5fd,
        fontSize = 11,
      },
    },
    {
      id = "runtimeStatus",
      type = "Label",
      x = 784,
      y = 454,
      w = 452,
      h = 16,
      props = { text = "Runtime idle" },
      style = {
        colour = 0xff7dd3fc,
        fontSize = 11,
      },
    },
    {
      id = "graphMetrics",
      type = "Label",
      x = 784,
      y = 474,
      w = 452,
      h = 16,
      props = { text = "runtime nodes=0 routes=0 | RMS in=0 wet=0 mix=0" },
      style = {
        colour = 0xff93c5fd,
        fontSize = 11,
      },
    },
    {
      id = "lastError",
      type = "Label",
      x = 784,
      y = 494,
      w = 452,
      h = 16,
      props = { text = "Error: none" },
      style = {
        colour = 0xfffca5a5,
        fontSize = 11,
      },
    },
    {
      id = "paramScrollInfo",
      type = "Label",
      x = 784,
      y = 514,
      w = 452,
      h = 16,
      props = { text = "Scroll: none" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 10,
      },
    },
    {
      id = "paramsBody",
      type = "Panel",
      x = 784,
      y = 538,
      w = 434,
      h = 150,
      style = {
        bg = 0x00000000,
        border = 0x00000000,
        borderWidth = 0,
        radius = 0,
      },
    },
    {
      id = "paramScrollSlider",
      type = "VSlider",
      x = 1226,
      y = 538,
      w = 14,
      h = 150,
      props = {
        min = 0,
        max = 1,
        step = 0,
        value = 1,
        showValue = false,
      },
      style = {
        colour = 0xff64748b,
        bg = 0xff1f2937,
      },
    },
  },
}
