return {
  id = "root",
  type = "Panel",
  x = 0,
  y = 0,
  w = 1280,
  h = 720,
  shellLayout = {
    mode = "fill",
    designW = 1280,
    designH = 720,
  },
  style = {
    bg = 0xff0a0f1a,
  },
  behavior = "ui/behaviors/main.lua",
  children = {
    {
      id = "header",
      type = "Panel",
      x = 12,
      y = 12,
      w = 1256,
      h = 40,
      style = {
        bg = 0x80111827,
        border = 0xff38bdf8,
        borderWidth = 1,
      },
    },
    {
      id = "title",
      type = "Label",
      x = 24,
      y = 12,
      w = 200,
      h = 40,
      props = { text = "◢ EXPERIMENTAL ◣" },
      style = {
        colour = 0xff22d3ee,
        fontSize = 20,
        fontStyle = FontStyle.bold,
      },
    },
    {
      id = "subtitle",
      type = "Label",
      x = 232,
      y = 12,
      w = 150,
      h = 40,
      props = { text = "Visual Playground" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 11,
      },
    },
    {
      id = "oscLabel",
      type = "Label",
      x = 392,
      y = 12,
      w = 864,
      h = 40,
      props = { text = "OSC: disabled" },
      style = {
        colour = 0xff64748b,
        fontSize = 10,
      },
    },

    {
      id = "particlePanel",
      type = "Panel",
      x = 12,
      y = 64,
      w = 414,
      h = 492,
      style = {
        bg = 0x151a2a,
        border = 0xff334155,
        borderWidth = 1,
        radius = 8,
      },
    },

    {
      id = "xyPanel",
      type = "Panel",
      x = 438,
      y = 64,
      w = 414,
      h = 492,
      style = {
        bg = 0x151a2a,
        border = 0xff334155,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "xyLabel",
      type = "Label",
      x = 446,
      y = 72,
      w = 398,
      h = 20,
      props = { text = "XY Pad (Control Space)" },
      style = {
        colour = 0xffa78bfa,
        fontSize = 12,
      },
    },
    {
      id = "xySentLabel",
      type = "Label",
      x = 446,
      y = 92,
      w = 398,
      h = 16,
      props = { text = "TX 0 - x=0.50 y=0.50" },
      style = {
        colour = 0xff22c55e,
        fontSize = 10,
      },
    },
    {
      id = "xyRecvLabel",
      type = "Label",
      x = 446,
      y = 108,
      w = 398,
      h = 16,
      props = { text = "RX 0 - x=0.50 y=0.50" },
      style = {
        colour = 0xfff59e0b,
        fontSize = 10,
      },
    },

    {
      id = "eqPanel",
      type = "Panel",
      x = 12,
      y = 568,
      w = 246,
      h = 140,
      style = {
        bg = 0x0a0f1a,
        border = 0xff475569,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "wavePanel",
      type = "Panel",
      x = 270,
      y = 568,
      w = 246,
      h = 140,
      style = {
        bg = 0x0a0f1a,
        border = 0xff475569,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "noisePanel",
      type = "Panel",
      x = 528,
      y = 568,
      w = 246,
      h = 140,
      style = {
        bg = 0x101520,
        border = 0xff475569,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "noiseLabel",
      type = "Label",
      x = 536,
      y = 572,
      w = 230,
      h = 18,
      props = { text = "Vector Field" },
      style = {
        colour = 0xfff59e0b,
        fontSize = 12,
      },
    },
    {
      id = "kaleidoPanel",
      type = "Panel",
      x = 786,
      y = 568,
      w = 246,
      h = 140,
      style = {
        bg = 0x0a0a15,
        border = 0xffec4899,
        borderWidth = 1,
        radius = 8,
      },
    },
    {
      id = "kaleidoLabel",
      type = "Label",
      x = 794,
      y = 572,
      w = 230,
      h = 18,
      props = { text = "Kaleidoscope" },
      style = {
        colour = 0xffec4899,
        fontSize = 12,
      },
    },
    {
      id = "glPanel",
      type = "Panel",
      x = 1044,
      y = 568,
      w = 224,
      h = 140,
      style = {
        bg = 0x0a0a15,
        border = 0xff00ffff,
        borderWidth = 2,
        radius = 8,
      },
    },
    {
      id = "glLabel",
      type = "Label",
      x = 1052,
      y = 572,
      w = 208,
      h = 18,
      props = { text = "OpenGL Pipeline" },
      style = {
        colour = 0xff00ffff,
        fontSize = 12,
      },
    },
    {
      id = "glStatusLabel",
      type = "Label",
      x = 1052,
      y = 590,
      w = 208,
      h = 14,
      props = { text = "First-party GL surface pending port" },
      style = {
        colour = 0xff94a3b8,
        fontSize = 10,
      },
    },
    {
      id = "glViewportHost",
      type = "Panel",
      x = 1052,
      y = 608,
      w = 208,
      h = 92,
      style = {
        bg = 0xff06101b,
        border = 0xff1f3b4d,
        borderWidth = 1,
        radius = 6,
      },
    },
    {
      id = "glViewportText",
      type = "Label",
      x = 1062,
      y = 636,
      w = 188,
      h = 28,
      props = { text = "GL surface intentionally parked until first-party port" },
      style = {
        colour = 0xff64748b,
        fontSize = 10,
        justification = Justify.centred,
      },
    },

    {
      id = "statusPanel",
      type = "Panel",
      x = 12,
      y = 685,
      w = 1256,
      h = 25,
      style = {
        bg = 0x80111827,
        border = 0xff374151,
        borderWidth = 1,
      },
    },
    {
      id = "layer1",
      type = "Panel",
      x = 20,
      y = 689,
      w = 308,
      h = 17,
      style = {
        bg = 0xff1e293b,
        border = 0xff475569,
        borderWidth = 1,
        radius = 4,
      },
      children = {
        {
          id = "layer1Label",
          type = "Label",
          x = 0,
          y = 0,
          w = 308,
          h = 17,
          props = { text = "L1" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 10,
            justification = Justify.centred,
          },
        },
      },
    },
    {
      id = "layer2",
      type = "Panel",
      x = 332,
      y = 689,
      w = 308,
      h = 17,
      style = {
        bg = 0xff1e293b,
        border = 0xff475569,
        borderWidth = 1,
        radius = 4,
      },
      children = {
        {
          id = "layer2Label",
          type = "Label",
          x = 0,
          y = 0,
          w = 308,
          h = 17,
          props = { text = "L2" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 10,
            justification = Justify.centred,
          },
        },
      },
    },
    {
      id = "layer3",
      type = "Panel",
      x = 644,
      y = 689,
      w = 308,
      h = 17,
      style = {
        bg = 0xff1e293b,
        border = 0xff475569,
        borderWidth = 1,
        radius = 4,
      },
      children = {
        {
          id = "layer3Label",
          type = "Label",
          x = 0,
          y = 0,
          w = 308,
          h = 17,
          props = { text = "L3" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 10,
            justification = Justify.centred,
          },
        },
      },
    },
    {
      id = "layer4",
      type = "Panel",
      x = 956,
      y = 689,
      w = 308,
      h = 17,
      style = {
        bg = 0xff1e293b,
        border = 0xff475569,
        borderWidth = 1,
        radius = 4,
      },
      children = {
        {
          id = "layer4Label",
          type = "Label",
          x = 0,
          y = 0,
          w = 308,
          h = 17,
          props = { text = "L4" },
          style = {
            colour = 0xff94a3b8,
            fontSize = 10,
            justification = Justify.centred,
          },
        },
      },
    },
  },
}
