package.path = "UserScripts/projects/Main/lib/?.lua;" .. package.path
local pb = require("parameter_binder")
local results = {}

local function add(name, ...)
  local args = {}
  for i = 1, select("#", ...) do
    args[i] = tostring(select(i, ...))
  end
  local key = name .. "(" .. table.concat(args, ",") .. ")"
  local ok, val = pcall(pb[name], ...)
  if ok then
    table.insert(results, key .. "=" .. tostring(val))
  else
    table.insert(results, key .. "=ERROR:" .. tostring(val))
  end
end


add("voiceFreqPath", 1)
add("voiceFreqPath", 16)
add("voiceFreqPath", 32)
add("voiceAmpPath", 1)
add("voiceAmpPath", 16)
add("voiceAmpPath", 32)
add("voiceGatePath", 1)
add("voiceGatePath", 16)
add("voiceGatePath", 32)
add("eq8BandEnabledPath", 1, 1)
add("eq8BandEnabledPath", 1, 4)
add("eq8BandEnabledPath", 1, 8)
add("eq8BandEnabledPath", 16, 1)
add("eq8BandTypePath", 1, 1)
add("eq8BandTypePath", 1, 4)
add("eq8BandTypePath", 1, 8)
add("eq8BandTypePath", 16, 1)
add("eq8BandFreqPath", 1, 1)
add("eq8BandFreqPath", 1, 4)
add("eq8BandFreqPath", 1, 8)
add("eq8BandFreqPath", 16, 1)
add("eq8BandGainPath", 1, 1)
add("eq8BandGainPath", 1, 4)
add("eq8BandGainPath", 1, 8)
add("eq8BandGainPath", 16, 1)
add("eq8BandQPath", 1, 1)
add("eq8BandQPath", 1, 4)
add("eq8BandQPath", 1, 8)
add("eq8BandQPath", 16, 1)
add("rackAudioStagePath", 1)
add("rackAudioStagePath", 16)
add("rackAudioStagePath", 32)
add("rackAudioSourcePath", 1)
add("rackAudioSourcePath", 16)
add("rackAudioSourcePath", 32)
add("dynamicEqBasePath", 1)
add("dynamicEqBasePath", 16)
add("dynamicEqBasePath", 32)
add("dynamicEqMixPath", 1)
add("dynamicEqMixPath", 16)
add("dynamicEqMixPath", 32)
add("dynamicEqOutputPath", 1)
add("dynamicEqOutputPath", 16)
add("dynamicEqOutputPath", 32)
add("dynamicEqBandEnabledPath", 1, 1)
add("dynamicEqBandEnabledPath", 1, 4)
add("dynamicEqBandEnabledPath", 1, 8)
add("dynamicEqBandEnabledPath", 16, 1)
add("dynamicEqBandTypePath", 1, 1)
add("dynamicEqBandTypePath", 1, 4)
add("dynamicEqBandTypePath", 1, 8)
add("dynamicEqBandTypePath", 16, 1)
add("dynamicEqBandFreqPath", 1, 1)
add("dynamicEqBandFreqPath", 1, 4)
add("dynamicEqBandFreqPath", 1, 8)
add("dynamicEqBandFreqPath", 16, 1)
add("dynamicEqBandGainPath", 1, 1)
add("dynamicEqBandGainPath", 1, 4)
add("dynamicEqBandGainPath", 1, 8)
add("dynamicEqBandGainPath", 16, 1)
add("dynamicEqBandQPath", 1, 1)
add("dynamicEqBandQPath", 1, 4)
add("dynamicEqBandQPath", 1, 8)
add("dynamicEqBandQPath", 16, 1)
add("dynamicFxBasePath", 1)
add("dynamicFxBasePath", 16)
add("dynamicFxBasePath", 32)
add("dynamicAdsrBasePath", 1)
add("dynamicAdsrBasePath", 16)
add("dynamicAdsrBasePath", 32)
add("dynamicAdsrAttackPath", 1)
add("dynamicAdsrAttackPath", 16)
add("dynamicAdsrAttackPath", 32)
add("dynamicAdsrDecayPath", 1)
add("dynamicAdsrDecayPath", 16)
add("dynamicAdsrDecayPath", 32)
add("dynamicAdsrSustainPath", 1)
add("dynamicAdsrSustainPath", 16)
add("dynamicAdsrSustainPath", 32)
add("dynamicAdsrReleasePath", 1)
add("dynamicAdsrReleasePath", 16)
add("dynamicAdsrReleasePath", 32)
add("dynamicArpBasePath", 1)
add("dynamicArpBasePath", 16)
add("dynamicArpBasePath", 32)
add("dynamicArpRatePath", 1)
add("dynamicArpRatePath", 16)
add("dynamicArpRatePath", 32)
add("dynamicArpModePath", 1)
add("dynamicArpModePath", 16)
add("dynamicArpModePath", 32)
add("dynamicArpOctavesPath", 1)
add("dynamicArpOctavesPath", 16)
add("dynamicArpOctavesPath", 32)
add("dynamicArpGateLengthPath", 1)
add("dynamicArpGateLengthPath", 16)
add("dynamicArpGateLengthPath", 32)
add("dynamicArpHoldPath", 1)
add("dynamicArpHoldPath", 16)
add("dynamicArpHoldPath", 32)
add("dynamicTransposeBasePath", 1)
add("dynamicTransposeBasePath", 16)
add("dynamicTransposeBasePath", 32)
add("dynamicTransposeSemitonesPath", 1)
add("dynamicTransposeSemitonesPath", 16)
add("dynamicTransposeSemitonesPath", 32)
add("dynamicVelocityMapperBasePath", 1)
add("dynamicVelocityMapperBasePath", 16)
add("dynamicVelocityMapperBasePath", 32)
add("dynamicVelocityMapperAmountPath", 1)
add("dynamicVelocityMapperAmountPath", 16)
add("dynamicVelocityMapperAmountPath", 32)
add("dynamicVelocityMapperCurvePath", 1)
add("dynamicVelocityMapperCurvePath", 16)
add("dynamicVelocityMapperCurvePath", 32)
add("dynamicVelocityMapperOffsetPath", 1)
add("dynamicVelocityMapperOffsetPath", 16)
add("dynamicVelocityMapperOffsetPath", 32)
add("dynamicScaleQuantizerBasePath", 1)
add("dynamicScaleQuantizerBasePath", 16)
add("dynamicScaleQuantizerBasePath", 32)
add("dynamicScaleQuantizerRootPath", 1)
add("dynamicScaleQuantizerRootPath", 16)
add("dynamicScaleQuantizerRootPath", 32)
add("dynamicScaleQuantizerScalePath", 1)
add("dynamicScaleQuantizerScalePath", 16)
add("dynamicScaleQuantizerScalePath", 32)
add("dynamicScaleQuantizerDirectionPath", 1)
add("dynamicScaleQuantizerDirectionPath", 16)
add("dynamicScaleQuantizerDirectionPath", 32)
add("dynamicNoteFilterBasePath", 1)
add("dynamicNoteFilterBasePath", 16)
add("dynamicNoteFilterBasePath", 32)
add("dynamicNoteFilterLowPath", 1)
add("dynamicNoteFilterLowPath", 16)
add("dynamicNoteFilterLowPath", 32)
add("dynamicNoteFilterHighPath", 1)
add("dynamicNoteFilterHighPath", 16)
add("dynamicNoteFilterHighPath", 32)
add("dynamicNoteFilterModePath", 1)
add("dynamicNoteFilterModePath", 16)
add("dynamicNoteFilterModePath", 32)
add("dynamicAttenuverterBiasBasePath", 1)
add("dynamicAttenuverterBiasBasePath", 16)
add("dynamicAttenuverterBiasBasePath", 32)
add("dynamicAttenuverterBiasAmountPath", 1)
add("dynamicAttenuverterBiasAmountPath", 16)
add("dynamicAttenuverterBiasAmountPath", 32)
add("dynamicAttenuverterBiasBiasPath", 1)
add("dynamicAttenuverterBiasBiasPath", 16)
add("dynamicAttenuverterBiasBiasPath", 32)
add("dynamicRangeMapperBasePath", 1)
add("dynamicRangeMapperBasePath", 16)
add("dynamicRangeMapperBasePath", 32)
add("dynamicRangeMapperMinPath", 1)
add("dynamicRangeMapperMinPath", 16)
add("dynamicRangeMapperMinPath", 32)
add("dynamicRangeMapperMaxPath", 1)
add("dynamicRangeMapperMaxPath", 16)
add("dynamicRangeMapperMaxPath", 32)
add("dynamicRangeMapperModePath", 1)
add("dynamicRangeMapperModePath", 16)
add("dynamicRangeMapperModePath", 32)
add("dynamicLfoBasePath", 1)
add("dynamicLfoBasePath", 16)
add("dynamicLfoBasePath", 32)
add("dynamicLfoRatePath", 1)
add("dynamicLfoRatePath", 16)
add("dynamicLfoRatePath", 32)
add("dynamicLfoShapePath", 1)
add("dynamicLfoShapePath", 16)
add("dynamicLfoShapePath", 32)
add("dynamicLfoDepthPath", 1)
add("dynamicLfoDepthPath", 16)
add("dynamicLfoDepthPath", 32)
add("dynamicLfoPhasePath", 1)
add("dynamicLfoPhasePath", 16)
add("dynamicLfoPhasePath", 32)
add("dynamicLfoRetrigPath", 1)
add("dynamicLfoRetrigPath", 16)
add("dynamicLfoRetrigPath", 32)
add("dynamicSlewBasePath", 1)
add("dynamicSlewBasePath", 16)
add("dynamicSlewBasePath", 32)
add("dynamicSlewRisePath", 1)
add("dynamicSlewRisePath", 16)
add("dynamicSlewRisePath", 32)
add("dynamicSlewFallPath", 1)
add("dynamicSlewFallPath", 16)
add("dynamicSlewFallPath", 32)
add("dynamicSlewShapePath", 1)
add("dynamicSlewShapePath", 16)
add("dynamicSlewShapePath", 32)
add("dynamicSampleHoldBasePath", 1)
add("dynamicSampleHoldBasePath", 16)
add("dynamicSampleHoldBasePath", 32)
add("dynamicSampleHoldModePath", 1)
add("dynamicSampleHoldModePath", 16)
add("dynamicSampleHoldModePath", 32)
add("dynamicCompareBasePath", 1)
add("dynamicCompareBasePath", 16)
add("dynamicCompareBasePath", 32)
add("dynamicCompareThresholdPath", 1)
add("dynamicCompareThresholdPath", 16)
add("dynamicCompareThresholdPath", 32)
add("dynamicCompareHysteresisPath", 1)
add("dynamicCompareHysteresisPath", 16)
add("dynamicCompareHysteresisPath", 32)
add("dynamicCompareDirectionPath", 1)
add("dynamicCompareDirectionPath", 16)
add("dynamicCompareDirectionPath", 32)
add("dynamicCvMixBasePath", 1)
add("dynamicCvMixBasePath", 16)
add("dynamicCvMixBasePath", 32)
add("dynamicCvMixLevelPath", 1, 1)
add("dynamicCvMixLevelPath", 1, 4)
add("dynamicCvMixLevelPath", 1, 8)
add("dynamicCvMixLevelPath", 16, 1)
add("dynamicCvMixOffsetPath", 1)
add("dynamicCvMixOffsetPath", 16)
add("dynamicCvMixOffsetPath", 32)
add("dynamicOscillatorBasePath", 1)
add("dynamicOscillatorBasePath", 16)
add("dynamicOscillatorBasePath", 32)
add("dynamicOscillatorWaveformPath", 1)
add("dynamicOscillatorWaveformPath", 16)
add("dynamicOscillatorWaveformPath", 32)
add("dynamicOscillatorRenderModePath", 1)
add("dynamicOscillatorRenderModePath", 16)
add("dynamicOscillatorRenderModePath", 32)
add("dynamicOscillatorAdditivePartialsPath", 1)
add("dynamicOscillatorAdditivePartialsPath", 16)
add("dynamicOscillatorAdditivePartialsPath", 32)
add("dynamicOscillatorAdditiveTiltPath", 1)
add("dynamicOscillatorAdditiveTiltPath", 16)
add("dynamicOscillatorAdditiveTiltPath", 32)
add("dynamicOscillatorAdditiveDriftPath", 1)
add("dynamicOscillatorAdditiveDriftPath", 16)
add("dynamicOscillatorAdditiveDriftPath", 32)
add("dynamicOscillatorDrivePath", 1)
add("dynamicOscillatorDrivePath", 16)
add("dynamicOscillatorDrivePath", 32)
add("dynamicOscillatorDriveShapePath", 1)
add("dynamicOscillatorDriveShapePath", 16)
add("dynamicOscillatorDriveShapePath", 32)
add("dynamicOscillatorDriveBiasPath", 1)
add("dynamicOscillatorDriveBiasPath", 16)
add("dynamicOscillatorDriveBiasPath", 32)
add("dynamicOscillatorPulseWidthPath", 1)
add("dynamicOscillatorPulseWidthPath", 16)
add("dynamicOscillatorPulseWidthPath", 32)
add("dynamicOscillatorUnisonPath", 1)
add("dynamicOscillatorUnisonPath", 16)
add("dynamicOscillatorUnisonPath", 32)
add("dynamicOscillatorDetunePath", 1)
add("dynamicOscillatorDetunePath", 16)
add("dynamicOscillatorDetunePath", 32)
add("dynamicOscillatorSpreadPath", 1)
add("dynamicOscillatorSpreadPath", 16)
add("dynamicOscillatorSpreadPath", 32)
add("dynamicOscillatorOutputPath", 1)
add("dynamicOscillatorOutputPath", 16)
add("dynamicOscillatorOutputPath", 32)
add("dynamicOscillatorManualPitchPath", 1)
add("dynamicOscillatorManualPitchPath", 16)
add("dynamicOscillatorManualPitchPath", 32)
add("dynamicOscillatorManualLevelPath", 1)
add("dynamicOscillatorManualLevelPath", 16)
add("dynamicOscillatorManualLevelPath", 32)
add("dynamicOscillatorVoiceGatePath", 1, 1)
add("dynamicOscillatorVoiceGatePath", 1, 4)
add("dynamicOscillatorVoiceGatePath", 1, 8)
add("dynamicOscillatorVoiceGatePath", 16, 1)
add("dynamicOscillatorVoiceVOctPath", 1, 1)
add("dynamicOscillatorVoiceVOctPath", 1, 4)
add("dynamicOscillatorVoiceVOctPath", 1, 8)
add("dynamicOscillatorVoiceVOctPath", 16, 1)
add("dynamicOscillatorVoiceFmPath", 1, 1)
add("dynamicOscillatorVoiceFmPath", 1, 4)
add("dynamicOscillatorVoiceFmPath", 1, 8)
add("dynamicOscillatorVoiceFmPath", 16, 1)
add("dynamicOscillatorVoicePwCvPath", 1, 1)
add("dynamicOscillatorVoicePwCvPath", 1, 4)
add("dynamicOscillatorVoicePwCvPath", 1, 8)
add("dynamicOscillatorVoicePwCvPath", 16, 1)
add("dynamicSampleBasePath", 1)
add("dynamicSampleBasePath", 16)
add("dynamicSampleBasePath", 32)
add("dynamicSampleSourcePath", 1)
add("dynamicSampleSourcePath", 16)
add("dynamicSampleSourcePath", 32)
add("dynamicSampleCaptureTriggerPath", 1)
add("dynamicSampleCaptureTriggerPath", 16)
add("dynamicSampleCaptureTriggerPath", 32)
add("dynamicSampleCaptureBarsPath", 1)
add("dynamicSampleCaptureBarsPath", 16)
add("dynamicSampleCaptureBarsPath", 32)
add("dynamicSampleCaptureModePath", 1)
add("dynamicSampleCaptureModePath", 16)
add("dynamicSampleCaptureModePath", 32)
add("dynamicSampleCaptureStartOffsetPath", 1)
add("dynamicSampleCaptureStartOffsetPath", 16)
add("dynamicSampleCaptureStartOffsetPath", 32)
add("dynamicSampleCapturedLengthMsPath", 1)
add("dynamicSampleCapturedLengthMsPath", 16)
add("dynamicSampleCapturedLengthMsPath", 32)
add("dynamicSampleCaptureRecordingPath", 1)
add("dynamicSampleCaptureRecordingPath", 16)
add("dynamicSampleCaptureRecordingPath", 32)
add("dynamicSampleCaptureWriteOffsetPath", 1)
add("dynamicSampleCaptureWriteOffsetPath", 16)
add("dynamicSampleCaptureWriteOffsetPath", 32)
add("dynamicSamplePitchMapEnabledPath", 1)
add("dynamicSamplePitchMapEnabledPath", 16)
add("dynamicSamplePitchMapEnabledPath", 32)
add("dynamicSamplePitchModePath", 1)
add("dynamicSamplePitchModePath", 16)
add("dynamicSamplePitchModePath", 32)
add("dynamicSamplePvocFFTOrderPath", 1)
add("dynamicSamplePvocFFTOrderPath", 16)
add("dynamicSamplePvocFFTOrderPath", 32)
add("dynamicSamplePvocTimeStretchPath", 1)
add("dynamicSamplePvocTimeStretchPath", 16)
add("dynamicSamplePvocTimeStretchPath", 32)
add("dynamicSampleRootNotePath", 1)
add("dynamicSampleRootNotePath", 16)
add("dynamicSampleRootNotePath", 32)
add("dynamicSampleUnisonPath", 1)
add("dynamicSampleUnisonPath", 16)
add("dynamicSampleUnisonPath", 32)
add("dynamicSampleDetunePath", 1)
add("dynamicSampleDetunePath", 16)
add("dynamicSampleDetunePath", 32)
add("dynamicSampleSpreadPath", 1)
add("dynamicSampleSpreadPath", 16)
add("dynamicSampleSpreadPath", 32)
add("dynamicSamplePlayStartPath", 1)
add("dynamicSamplePlayStartPath", 16)
add("dynamicSamplePlayStartPath", 32)
add("dynamicSampleLoopStartPath", 1)
add("dynamicSampleLoopStartPath", 16)
add("dynamicSampleLoopStartPath", 32)
add("dynamicSampleLoopLenPath", 1)
add("dynamicSampleLoopLenPath", 16)
add("dynamicSampleLoopLenPath", 32)
add("dynamicSampleCrossfadePath", 1)
add("dynamicSampleCrossfadePath", 16)
add("dynamicSampleCrossfadePath", 32)
add("dynamicSampleRetriggerPath", 1)
add("dynamicSampleRetriggerPath", 16)
add("dynamicSampleRetriggerPath", 32)
add("dynamicSampleOutputPath", 1)
add("dynamicSampleOutputPath", 16)
add("dynamicSampleOutputPath", 32)
add("dynamicSampleInputSourcePath", 1)
add("dynamicSampleInputSourcePath", 16)
add("dynamicSampleInputSourcePath", 32)
add("dynamicSampleVoiceGatePath", 1, 1)
add("dynamicSampleVoiceGatePath", 1, 4)
add("dynamicSampleVoiceGatePath", 1, 8)
add("dynamicSampleVoiceGatePath", 16, 1)
add("dynamicSampleVoiceVOctPath", 1, 1)
add("dynamicSampleVoiceVOctPath", 1, 4)
add("dynamicSampleVoiceVOctPath", 1, 8)
add("dynamicSampleVoiceVOctPath", 16, 1)
add("dynamicBlendSimpleBasePath", 1)
add("dynamicBlendSimpleBasePath", 16)
add("dynamicBlendSimpleBasePath", 32)
add("dynamicBlendSimpleModePath", 1)
add("dynamicBlendSimpleModePath", 16)
add("dynamicBlendSimpleModePath", 32)
add("dynamicBlendSimpleBlendAmountPath", 1)
add("dynamicBlendSimpleBlendAmountPath", 16)
add("dynamicBlendSimpleBlendAmountPath", 32)
add("dynamicBlendSimpleBlendModAmountPath", 1)
add("dynamicBlendSimpleBlendModAmountPath", 16)
add("dynamicBlendSimpleBlendModAmountPath", 32)
add("dynamicBlendSimpleOutputPath", 1)
add("dynamicBlendSimpleOutputPath", 16)
add("dynamicBlendSimpleOutputPath", 32)
add("dynamicBlendSimpleBSourcePath", 1)
add("dynamicBlendSimpleBSourcePath", 16)
add("dynamicBlendSimpleBSourcePath", 32)
add("dynamicFilterBasePath", 1)
add("dynamicFilterBasePath", 16)
add("dynamicFilterBasePath", 32)
add("dynamicFilterTypePath", 1)
add("dynamicFilterTypePath", 16)
add("dynamicFilterTypePath", 32)
add("dynamicFilterCutoffPath", 1)
add("dynamicFilterCutoffPath", 16)
add("dynamicFilterCutoffPath", 32)
add("dynamicFilterResonancePath", 1)
add("dynamicFilterResonancePath", 16)
add("dynamicFilterResonancePath", 32)
add("dynamicFxTypePath", 1)
add("dynamicFxTypePath", 16)
add("dynamicFxTypePath", 32)
add("dynamicFxMixPath", 1)
add("dynamicFxMixPath", 16)
add("dynamicFxMixPath", 32)
add("dynamicFxParamPath", 1, 1)
add("dynamicFxParamPath", 1, 4)
add("dynamicFxParamPath", 1, 8)
add("dynamicFxParamPath", 16, 1)
add("fxParamPath", 1, 1)
add("fxParamPath", 1, 2)
add("matchFxParamPath", '/midi/synth/rack/eq/1/mix')
add("matchFxParamPath", '/midi/synth/rack/fx/3/type')
add("matchFxParamPath", '/midi/synth/rack/filter/2/cutoff')
add("matchFxParamPath", '/midi/synth/rack/sample/8/source')
add("matchFxParamPath", '/midi/synth/waveform')
add("matchFxParamPath", '/midi/synth/output')
add("matchFxParamPath", '/some/invalid/path')
add("isEq8Path", '/midi/synth/rack/eq/1/mix')
add("isEq8Path", '/midi/synth/rack/fx/3/type')
add("isEq8Path", '/midi/synth/rack/filter/2/cutoff')
add("isEq8Path", '/midi/synth/rack/sample/8/source')
add("isEq8Path", '/midi/synth/waveform')
add("isEq8Path", '/midi/synth/output')
add("isEq8Path", '/some/invalid/path')
add("matchDynamicEqPath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicEqPath", '/midi/synth/rack/fx/3/type')
add("matchDynamicEqPath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicEqPath", '/midi/synth/rack/sample/8/source')
add("matchDynamicEqPath", '/midi/synth/waveform')
add("matchDynamicEqPath", '/midi/synth/output')
add("matchDynamicEqPath", '/some/invalid/path')
add("matchDynamicFxPath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicFxPath", '/midi/synth/rack/fx/3/type')
add("matchDynamicFxPath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicFxPath", '/midi/synth/rack/sample/8/source')
add("matchDynamicFxPath", '/midi/synth/waveform')
add("matchDynamicFxPath", '/midi/synth/output')
add("matchDynamicFxPath", '/some/invalid/path')
add("matchDynamicAdsrPath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicAdsrPath", '/midi/synth/rack/fx/3/type')
add("matchDynamicAdsrPath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicAdsrPath", '/midi/synth/rack/sample/8/source')
add("matchDynamicAdsrPath", '/midi/synth/waveform')
add("matchDynamicAdsrPath", '/midi/synth/output')
add("matchDynamicAdsrPath", '/some/invalid/path')
add("matchDynamicArpPath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicArpPath", '/midi/synth/rack/fx/3/type')
add("matchDynamicArpPath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicArpPath", '/midi/synth/rack/sample/8/source')
add("matchDynamicArpPath", '/midi/synth/waveform')
add("matchDynamicArpPath", '/midi/synth/output')
add("matchDynamicArpPath", '/some/invalid/path')
add("matchDynamicFilterPath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicFilterPath", '/midi/synth/rack/fx/3/type')
add("matchDynamicFilterPath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicFilterPath", '/midi/synth/rack/sample/8/source')
add("matchDynamicFilterPath", '/midi/synth/waveform')
add("matchDynamicFilterPath", '/midi/synth/output')
add("matchDynamicFilterPath", '/some/invalid/path')
add("matchDynamicOscillatorPath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicOscillatorPath", '/midi/synth/rack/fx/3/type')
add("matchDynamicOscillatorPath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicOscillatorPath", '/midi/synth/rack/sample/8/source')
add("matchDynamicOscillatorPath", '/midi/synth/waveform')
add("matchDynamicOscillatorPath", '/midi/synth/output')
add("matchDynamicOscillatorPath", '/some/invalid/path')
add("matchDynamicOscillatorVoicePath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicOscillatorVoicePath", '/midi/synth/rack/fx/3/type')
add("matchDynamicOscillatorVoicePath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicOscillatorVoicePath", '/midi/synth/rack/sample/8/source')
add("matchDynamicOscillatorVoicePath", '/midi/synth/waveform')
add("matchDynamicOscillatorVoicePath", '/midi/synth/output')
add("matchDynamicOscillatorVoicePath", '/some/invalid/path')
add("matchDynamicSamplePath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicSamplePath", '/midi/synth/rack/fx/3/type')
add("matchDynamicSamplePath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicSamplePath", '/midi/synth/rack/sample/8/source')
add("matchDynamicSamplePath", '/midi/synth/waveform')
add("matchDynamicSamplePath", '/midi/synth/output')
add("matchDynamicSamplePath", '/some/invalid/path')
add("matchDynamicSampleVoicePath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicSampleVoicePath", '/midi/synth/rack/fx/3/type')
add("matchDynamicSampleVoicePath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicSampleVoicePath", '/midi/synth/rack/sample/8/source')
add("matchDynamicSampleVoicePath", '/midi/synth/waveform')
add("matchDynamicSampleVoicePath", '/midi/synth/output')
add("matchDynamicSampleVoicePath", '/some/invalid/path')
add("matchDynamicBlendSimplePath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicBlendSimplePath", '/midi/synth/rack/fx/3/type')
add("matchDynamicBlendSimplePath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicBlendSimplePath", '/midi/synth/rack/sample/8/source')
add("matchDynamicBlendSimplePath", '/midi/synth/waveform')
add("matchDynamicBlendSimplePath", '/midi/synth/output')
add("matchDynamicBlendSimplePath", '/some/invalid/path')
add("matchDynamicModulePath", '/midi/synth/rack/eq/1/mix')
add("matchDynamicModulePath", '/midi/synth/rack/fx/3/type')
add("matchDynamicModulePath", '/midi/synth/rack/filter/2/cutoff')
add("matchDynamicModulePath", '/midi/synth/rack/sample/8/source')
add("matchDynamicModulePath", '/midi/synth/waveform')
add("matchDynamicModulePath", '/midi/synth/output')
add("matchDynamicModulePath", '/some/invalid/path')
add("matchRackAudioStagePath", '/midi/synth/rack/eq/1/mix')
add("matchRackAudioStagePath", '/midi/synth/rack/fx/3/type')
add("matchRackAudioStagePath", '/midi/synth/rack/filter/2/cutoff')
add("matchRackAudioStagePath", '/midi/synth/rack/sample/8/source')
add("matchRackAudioStagePath", '/midi/synth/waveform')
add("matchRackAudioStagePath", '/midi/synth/output')
add("matchRackAudioStagePath", '/some/invalid/path')
add("matchRackAudioSourcePath", '/midi/synth/rack/eq/1/mix')
add("matchRackAudioSourcePath", '/midi/synth/rack/fx/3/type')
add("matchRackAudioSourcePath", '/midi/synth/rack/filter/2/cutoff')
add("matchRackAudioSourcePath", '/midi/synth/rack/sample/8/source')
add("matchRackAudioSourcePath", '/midi/synth/waveform')
add("matchRackAudioSourcePath", '/midi/synth/output')
add("matchRackAudioSourcePath", '/some/invalid/path')

table.sort(results)
for _, line in ipairs(results) do
  print(line)
end
